import React from "react";
import '../css/SolutionsComponent.css'

export default function Solutions() {
    return(
        <React.Fragment>
            <div className="solutions-container">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent pharetra porta odio eu condimentum. Etiam volutpat sodales mollis. Maecenas quis scelerisque risus. Pellentesque id ornare nisi. Sed id magna sit amet metus vehicula maximus ac sollicitudin elit. Mauris commodo pretium pharetra. Sed porta nibh a tempus lacinia. Nam a nunc lacus. Etiam tempus, enim at consequat pretium, tortor nunc feugiat felis, id ultricies erat nulla sed turpis. Vestibulum sollicitudin odio quis erat dapibus vehicula. Fusce at sapien risus. In at ullamcorper magna, sit amet eleifend tellus.</p>
                <p>Vestibulum finibus mi sed dolor dictum, at placerat arcu aliquam. Nunc venenatis feugiat vehicula. Vestibulum semper elit ac nisi pharetra, nec condimentum magna ultrices. Quisque in eleifend risus. Pellentesque ipsum neque, pulvinar vel nisi sed, dictum bibendum diam. Quisque semper orci id sollicitudin cursus. Phasellus scelerisque sem id libero tempor, volutpat tristique quam ultricies. Vivamus eget magna justo. Praesent eget auctor sapien. Fusce quis rhoncus augue. Fusce ornare eros ac erat consectetur, eu luctus elit tempor. Sed commodo dui et diam vestibulum luctus. Aliquam ac consequat enim.</p>
                <p>Sed ac urna quis odio porta tincidunt eu at ligula. Maecenas vel bibendum sapien, id aliquet leo. Mauris mi ante, fermentum vel ullamcorper quis, volutpat in felis. Vivamus mattis magna eu tortor consequat imperdiet. Ut nibh ligula, vehicula eget sollicitudin ac, dapibus eu lectus. Nunc mollis purus eu rutrum blandit. Morbi quam velit, sagittis quis est quis, molestie convallis enim. In aliquam et velit a consectetur. Cras semper eu velit eu venenatis. Duis a massa enim.</p>
                <p>Quisque dui quam, venenatis non lacus quis, aliquet pharetra nulla. Donec vitae scelerisque velit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus eget orci massa. Donec luctus odio nibh, in egestas tortor vehicula vel. Nulla commodo dolor in lectus gravida, at aliquam tortor maximus. Integer auctor ante lectus, vel accumsan lacus feugiat non. Vestibulum posuere ante massa. Phasellus pellentesque nibh magna, eu lobortis est sollicitudin sed. Donec sit amet elit volutpat lorem vulputate luctus. Aliquam efficitur, mauris at fermentum commodo, mi odio laoreet felis, id feugiat magna ex in nisi. Vestibulum tristique, leo non mollis ullamcorper, nunc libero ullamcorper elit, at pulvinar metus mi vitae justo.</p>
                <p>Aliquam cursus justo lectus, id fermentum turpis porttitor quis. Sed posuere sapien nisl, sit amet lacinia elit eleifend id. Fusce efficitur dui aliquet libero imperdiet, id consectetur nisl tincidunt. Cras semper fermentum lorem id porta. Sed sit amet sagittis ligula, consectetur fringilla massa. Etiam placerat lacus quis ligula facilisis, ut placerat ligula porttitor. Quisque viverra vestibulum mauris, sed hendrerit ante viverra sed. Sed viverra bibendum quam, quis tristique nisl dapibus in. Quisque pellentesque tortor eu consectetur porttitor. Cras at dolor magna. Donec at maximus diam. Nullam nec magna dui. Phasellus porttitor ullamcorper convallis.</p>
                <p>Proin sem nisl, aliquet ut elit eget, suscipit ornare justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam commodo neque at odio egestas aliquam. Cras vestibulum, odio non tristique porta, justo purus aliquet nisl, in consectetur quam velit at leo. Aliquam erat urna, faucibus et leo vitae, aliquet ultricies sapien. Curabitur ac interdum ex. Pellentesque vehicula lacus quis quam eleifend egestas.</p>
                <p>Mauris dapibus scelerisque nunc id lobortis. Vestibulum vitae elit volutpat, dapibus dui iaculis, aliquam ipsum. Donec velit nisi, congue non risus eget, tempus lacinia erat. Phasellus iaculis porttitor nisi, a suscipit ipsum malesuada id. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla tristique elit et ornare vestibulum. Praesent pretium pretium odio eget pellentesque. Proin mattis velit vel libero faucibus, sed varius nisl posuere. Donec ullamcorper arcu diam, ultrices varius quam pretium ac. Etiam consectetur pharetra magna, nec cursus arcu suscipit et. Quisque nibh elit, dictum eget suscipit a, blandit eget tellus. Ut diam est, gravida vitae rutrum sit amet, cursus sed justo. Mauris nulla magna, auctor at tincidunt sit amet, sodales in erat. Quisque a ullamcorper eros. Cras placerat purus et enim ultrices mollis. Etiam ac risus vulputate, varius nisi quis, rhoncus lacus.</p>
                <p>Curabitur eu dolor eleifend ex blandit gravida vel ac ante. Praesent pulvinar justo in maximus volutpat. Mauris condimentum convallis venenatis. Quisque volutpat libero neque, a vulputate nisl scelerisque vel. Maecenas vulputate euismod libero ut egestas. Nunc eget mi nibh. Nullam tempor pulvinar nibh, vitae tincidunt augue. Nam a mauris viverra, porta neque vel, feugiat massa. Nulla ac nisi ac urna elementum pellentesque. Etiam nec fringilla dolor. Nunc vel mauris pretium, ullamcorper ligula sed, suscipit lectus. In auctor aliquam euismod. Aenean sollicitudin justo ac risus luctus, vitae imperdiet mauris feugiat. Praesent tortor lacus, faucibus vel velit ultrices, volutpat malesuada nunc.</p>
                <p>Morbi fringilla lectus placerat risus tincidunt pulvinar. Curabitur sed faucibus orci, sed ornare mi. Donec id mi risus. In imperdiet lacus vitae lectus tempor, in gravida quam pulvinar. Nunc vel libero suscipit, accumsan lorem ac, pharetra velit. Morbi faucibus blandit dolor non porttitor. Integer est neque, tristique a tristique at, aliquam in lacus. Etiam scelerisque nulla in laoreet eleifend. In dui est, imperdiet vitae vestibulum at, placerat in urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vestibulum non mi id leo placerat tincidunt. Vivamus dictum turpis vel ligula ullamcorper auctor. Morbi condimentum placerat mi eu faucibus. Fusce malesuada est quis nulla rhoncus fringilla.</p>
                <p>Nunc justo mauris, feugiat vitae arcu nec, finibus sagittis elit. Ut in massa porta, facilisis erat eget, convallis dolor. Ut mauris velit, viverra id suscipit quis, aliquam id est. Fusce tincidunt sem dui, id consequat risus imperdiet eu. In eget libero tempor, pellentesque urna non, suscipit velit. Curabitur pretium fringilla tellus et rutrum. Pellentesque at consectetur quam, vel aliquam tortor. Mauris et commodo lacus, eu tempor mauris.</p>
            </div>
        </React.Fragment>
    )
    
}
